{
 "title": "NodeJS Starter Dashboard",
 "panels": [
  {
   "title": "Awesome Node Pod CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{namespace=\"awesome-node\", pod=~\"awesome-node-.*\", container=\"\"}[3m])*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Awesome Node Pod Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"awesome-node\", pod=~\"awesome-node-.*\", container=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Awesome Node Reqeust Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{app=\"awesome-node\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Awesome Node - Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (rate(http_request_duration_seconds_count{app=\"awesome-node\"}[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Awesome Node Reqeust Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(sum by (le) (increase(http_request_duration_seconds_bucket{app=\"awesome-node\"}[$__rate_interval])), \"le\", \"Inf\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (increase(http_request_duration_seconds_bucket{app=\"awesome-node\", le=\"0.3\"}[1d])) / sum by (app) (increase(http_request_duration_seconds_count{app=\"awesome-node\"}[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Awesome Node Request Duration (Stacked All Buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{kubernetes_namespace=\"awesome-node\"}[3m]))\n",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  },
  {
   "title": "Awesome Node Request Duration (Unstacked Buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"0.03\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.003\"}[3m]))",
     "legendFormat": "0.003  <  t  <  0.03"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"0.1\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.03\"}[3m]))",
     "legendFormat": "0.03  <  t  <  0.1"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"0.3\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.1\"}[3m]))",
     "legendFormat": "0.1  <  t  < 0.3"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"1.5\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"0.3\"}[3m]))",
     "legendFormat": "0.3  <  t  <  1.5"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"10\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"1.5\"}[3m]))",
     "legendFormat": "1.5  <  t  <  10"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{le=\"+Inf\"}[3m])) - sum (rate(http_request_duration_seconds_bucket{le=\"10\"}[3m]))",
     "legendFormat": "10  <  t"
    }
   ]
  },
  {
   "title": "Container Restarts (last 3h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"awesome-node\"}[3h]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Awesome Node Request Duration (Stacked Buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app, le) (rate(http_request_duration_seconds_count{kubernetes_namespace=\"awesome-node\"}[3m]) - ignoring (le) group_right rate(http_request_duration_seconds_bucket{le!=\"+Inf\"}[3m]))",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(sum by (app) (rate(http_request_duration_seconds_bucket{app=\"awesome-node\", le=\"0.3\"}[2m])) / sum by (app) (rate(http_request_duration_seconds_count{app=\"awesome-node\"}[2m]))) * 100"
    }
   ]
  }
 ]
}