# This is a quick deployment script for running Jaeger's all-in-one on a development kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  type: ClusterIP
  ports:
    - name: udp-5775
      port: 5775
      protocol: UDP
    - name: udp-6831
      port: 6831
      protocol: UDP
    - name: udp-6832
      port: 6832
      protocol: UDP
    - name: tcp-5778
      port: 5778
    - name: tcp-16686
      port: 16686
    - name: tcp-14268
      port: 14268
    - name: tcp-14250
      port: 14250
    - name: tcp-9411
      port: 9411
